export const STATUS = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELAYED: 'DELAYED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  BODY_SHOP: 'BODY_SHOP',
  CANCELLED: 'CANCELLED',
  WATER_WASH_ASSIGNED: 'WATER_WASH_ASSIGNED',
  WATER_WASH_IN_PROGRESS: 'WATER_WASH_IN_PROGRESS',
  WATER_WASH_COMPLETED: 'WATER_WASH_COMPLETED',
};

export const STATUS_LABELS = {
  PENDING: 'Pending',
  ASSIGNED: 'Assigned',
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
  DELAYED: 'Delayed',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  READY: 'Ready for Delivery',
  DELIVERED: 'Delivered',
  BODY_SHOP: 'Body Shop',
  CANCELLED: 'Cancelled',
  MECHANICAL_ASSIGNMENT_PENDING: 'Mechanical Assignment Pending',
  MECHANICAL_ASSIGNED: 'Mechanical Assigned',
  MECHANICAL_IN_PROGRESS: 'Mechanical In Progress',
  MECHANICAL_COMPLETED: 'Mechanical Completed',
  BODY_SHOP_ASSIGNMENT_PENDING: 'Body Shop Assignment Pending',
  BODY_SHOP_ASSIGNED: 'Body Shop Assigned',
  BODY_SHOP_IN_PROGRESS: 'Body Shop In Progress',
  BODY_SHOP_COMPLETED: 'Body Shop Completed',
  WATER_WASH_ASSIGNMENT_PENDING: 'Water Wash Assignment Pending',
  WATER_WASH_ASSIGNED: 'Water Wash Assigned',
  WATER_WASH_IN_PROGRESS: 'Water Wash In Progress',
  WATER_WASH_COMPLETED: 'Water Wash Completed',
  READY_FOR_DELIVERY: 'Ready for Delivery',
  JOB_CARD_CREATED: 'Job Card Created',
  ENTRY_CREATED: 'Entry Created',
  EXITED: 'Exited',
  ACTIVE: 'Active',
  INACTIVE: 'Inactive',
};

export const STATUS_VARIANTS = {
  PENDING: 'warning',
  ASSIGNED: 'info',
  IN_PROGRESS: 'purple',
  COMPLETED: 'success',
  DELAYED: 'danger',
  APPROVED: 'success',
  REJECTED: 'danger',
  READY: 'primary',
  DELIVERED: 'secondary',
  BODY_SHOP: 'pink',
  CANCELLED: 'secondary',
  MECHANICAL_ASSIGNMENT_PENDING: 'warning',
  MECHANICAL_ASSIGNED: 'info',
  MECHANICAL_IN_PROGRESS: 'purple',
  MECHANICAL_COMPLETED: 'success',
  BODY_SHOP_ASSIGNMENT_PENDING: 'warning',
  BODY_SHOP_ASSIGNED: 'pink',
  BODY_SHOP_IN_PROGRESS: 'purple',
  BODY_SHOP_COMPLETED: 'success',
  WATER_WASH_ASSIGNMENT_PENDING: 'warning',
  WATER_WASH_ASSIGNED: 'info',
  WATER_WASH_IN_PROGRESS: 'info',
  WATER_WASH_COMPLETED: 'success',
  READY_FOR_DELIVERY: 'primary',
  JOB_CARD_CREATED: 'success',
  ENTRY_CREATED: 'success',
  EXITED: 'danger',
  ACTIVE: 'success',
  INACTIVE: 'danger',
};

